# ============ 生产环境配置 ============
spring:
  datasource:
    druid:  # druid连接池配置
      url: jdbc:mysql://192.168.12.41:3306/pfc_v2?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true  # 数据库URL
      username: root  # 数据库用户名
      password: root  # 数据库密码
      driverClassName: com.mysql.jdbc.Driver  # 数据库驱动类
      maxActive: 30  # 最大连接数
      minIdle: 5  # 最小保持的连接数
      maxWait: 10000  # 获取连接的最大等待时间
      validationQuery: 'SELECT 1'  # 解决Mysql8小时的问题，验证连接是否有效
      timeBetweenEvictionRunsMillis: 60000  # 空闲连接检查的时间间隔
      minEvictableIdleTimeMillis: 300000  # 空闲连接最小空闲时间
  redis:  # Redis配置
    host: 192.168.12.235
    port: 9999
    password: redis
    jedis:
      pool:
        min-idle: 10
        max-idle: 100
        max-wait: 1000
        max-active: 20
